### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by reggi** [mmckegg/json-query#10]
@mmckegg I would really love to be able to query a deep object or property and be able to map it, changing it's value and returning the new object. Is this possible? Let me know if you need more details.

**Comment by mmckegg** [comment]
@reggi: Think I know what you mean. Can you post a code snippet of how you think the API should work?

**Comment by reggi** [comment]
I have a nested `node` object structure like this:

```js
var nodes = [
  {
    props: {
      type: 'pants'
    }
    nodes: [
      {
        props: {
          type: 'shorts'
        }
      }
    ]
  },
  {
    props: {
      type: 'jacket'
    }
  },
  {
    props: {
      type: 'pants'
    }
  }
]
```

I'm looking for aways to do preform the following operations on this data. I'm working with recursive data, which I don't think your library will support out of the box, I'll have to so some stuff to get all the features I want. Here's the full list if your interested.

* find -> Return found root node(s)
* findRecursive -> Return found node(s)
* findFirst -> Return first fount root found node(s)
* findFirstRecursive -> Return first found node node(s)

All maps should array of all node(s)

* map -> map callback called on found root node(s)
* mapRecursive -> map callback called on found node(s)
* mapFirst -> map callback called on first found root node
* mapFirstRecursive -> map callback called on first found node

I'm unsure if the original data should be cloned or the orignal object should be edited

```js
jsonQuery('[props.type=pants]', {
  data: data
}).map(function (node) {
  node.price = '5'
  return node
})
```

or

```js
jsonQuery('[props.type=pants]', {
  data: data,
  map: function (node) {
    node.price = '5'
    return node
  })
})
```

Can I query and return multiple objects back or does it always return one value?

**Comment by mmckegg** [comment]
Currently always returns one result only. 

Have considered adding a `multiple` option which would allow using it as a filter. Or maybe it should be a new syntax option so that the result can be passed to a helper function (specified by locals).

This module has fallen quite out of date and could use a lot of work to make it useful :)

**Comment by reggi** [comment]
Hey @mmckegg here's what I made to solve my issues, perhaps you can find it useful as well. 

https://gist.github.com/reggi/a2dc6342186ae63b12da
