### ISSUE TITLE
Support returning multiple results

### ISSUE THREAD

**Issue by aurium** [mmckegg/json-query#13]
As [proposed in a comment](https://github.com/mmckegg/json-query/pull/11#issuecomment-176511741), array filter could return all matched itens as value, when option `multiple` is `true`.

**Comment by ofersadgat** [comment]
I agree. What I would really like to be able to do is: 

```js
var jsonQuery = require('json-query')
 
var data = {
  people: [
    {name: 'Matt', country: 'NZ'},
    {name: 'Pete', country: 'AU'}
  ]
}
 
jsonQuery('people[].name', {
  data: data
}) //=> ['Matt', 'Pete'] 
```

**Comment by mmckegg** [comment]
Instead of `multiple: true` something like this could also work:

```js
// adding an asterisk inside selector would return all matching results instead of just first
jsonQuery('people[*country=NZ]', { data: data }) 
```

And in conjunction with @ofersadgat's PR, you could do this:

```js
jsonQuery('people[*country=NZ].name', { data: data }) // outputs all of the names where NZ is country
```

I might give this a go and see how it works!
