### ISSUE TITLE
Query help - hitting a wall

### ISSUE THREAD

**Issue by mwkrieger** [mmckegg/json-query#17]
Hi, 

I'm hitting a wall on how to query a particular structure. A simplified example of what I'm trying to work with is as follows: 

```
var data = {
    docs: [
        languages: [{
            active: true,
            language: 'English',
            locale: 'EN-US'
        }, {
            active: true,
            language: 'Spanish',
            locale: 'ES-US'
        }]
    ]
}
```
What I'm trying to return if I query language=Spanish is:
```
{
      active: true,
      language: 'Spanish',
      locale: 'ES-US'
 }
```

I have tried every permutation I can think of and just can't get the expected results. 

Can someone point me in the right direction?

**Comment by mmckegg** [comment]
`jsonQuery("docs.languages[language=Spanish]", {data: data}).value` should work. If not, something strange is happening.

**Comment by mwkrieger** [comment]
That absolutely did the trick, thank you! I was putting in too many brackets - I was trying docs[].languages[].language=Spanish and every other possible combination of that. 

As a follow up, is there a way to query two or more fields at the same time - so, say, language=Spanish AND enabled=true? 

Again, thanks for your help.

**Comment by abhirathore2006** [comment]
is there any way to search with combination of And, or like below e.g.
language=spanish or english or some_more _options AND active=true AND some more conditions..

**Comment by mmckegg** [comment]
This didn't use to be possible, but is now supported since version **2.0.0**. 

There's a couple of options:

```js
// Use boolean logic:
jsonQuery("docs.languages[language=Spanish & enabled=true]", {data: data}).value

// Or you can use a helper function:
jsonQuery("docs.languages[:active]", {data: data, helpers: {
  active: function (input) {
    return input.enabled && input.language === 'Spanish'
  }
}}).value

// and don't forget that if you want multiple results, use *
jsonQuery("docs.languages[* language=Spanish & enabled=true]", {data: data}).value
```
