### ISSUE TITLE
Problem with deep queries

### ISSUE THREAD

**Issue by AlexR77** [mmckegg/json-query#19]
Hi there,

I am really happy with json-query, but am currently stuck with something I want to achieve. Before investing even more time into this, I wanted to ask if you see any obvious mistake in the way I am using this.

My task:
I want to select something based on another field.

Here is an abstract of the Google response I am using:
```
{
	"results" : [
	{
	    "address_components" : [
	    	…
	    ],
	    "formatted_address" : "street address 1",
	    …
	    "type" : [
	    	"street_address"
		]
	}
	{
	   "address_components" : [
	    	…
	    ],
	    "formatted_address" : "street address 2",
	    …
	    "type" : [
	    	"administrative_area_level_1", 
	    	"political"	
		],
	}
	]
}
```

I want to select the formatted_address based on the type. I get it working for the first entry with `jsonQuery('results[types=street_address].formatted_address', {data: response}).value `, where the array length of types == 1, but not for the second value of results.

I also tried results[][types=administrative_area_level_1].formatted_address.

Am I interpreting the deep query logic wrong?

Thanks,
Alex

**Comment by mmckegg** [comment]
The deep queries only work for selecting fields, not filtering arrays.

Since version **2.0.0** you can probably do what you want by creating a helper function:

```js
var helpers = {
  includes: function (input, search) {
     return input.indexOf(search) !== -1
  }
}

jsonQuery('results[type:includes(administrative_area_level_1)].formatted_address', {
  data: response,
  locals: helpers
}).value
```

**Comment by AlexR77** [comment]
Hi,

thanks for your help, but I get a `TypeError: Cannot read property 'indexOf' of undefined` when doing that. 

For the helper function:
Where do you set the parameters input and search?

**Comment by mmckegg** [comment]
`input` will be the value of the `type` field for that particular item, and `search` will be whatever is put in brackets after the `:includes`.

That error is probably being caused by an item that doesn't have a valid `type` property. Or is it `types`? 

```js
var helpers = {
  includes: function (input, search) {
     // check to see if valid first
     if (input && input.indexOf) {
        return input.indexOf(search) !== -1
     }
  }
}

// make sure that the correct field (types/type) is specified here
jsonQuery('results[types:includes(administrative_area_level_1)].formatted_address', {
  data: response,
  locals: helpers
}).value
```

**Comment by AlexR77** [comment]
Thanks, understanding the parameters helped. Btw. it was types not type.
