### ISSUE TITLE
"select" query not working for DeepQuery

### ISSUE THREAD

**Issue by JaySardhara** [mmckegg/json-query#21]
Hi,

I am trying select query as helper function by taking reference from your given example.  I am able to fetch data without "select" query from my JSON. But when I use helper function, somehow no data is returned.

![image](https://cloud.githubusercontent.com/assets/6151138/16889297/2c486090-4a9a-11e6-830a-9c9287da0143.png)

When I run below code, `{}` are returned.
![image](https://cloud.githubusercontent.com/assets/6151138/16889306/39e4b082-4a9a-11e6-8a3b-d05d1ddd73fd.png)

Thanks.

**Comment by mmckegg** [comment]
From your example it looks like `item` (which is inside of `data`) contains the items.

Try `'data.item:select(id, details)'`

**Comment by mmckegg** [comment]
whoops, you said Deep Query. Sorry missed that. Yeah, I don't think you can use helpers with deep queries. But I think you can use `'data[*]:select(id, details)'`. Not 100% sure though.
