### ISSUE TITLE
Problem with query

### ISSUE THREAD

**Issue by pbreah** [mmckegg/json-query#24]
Having the following data:

```javascript
const data = {
  "other_data" : "non important data",
  "exp" : {
      "Book 1" : {
        "other_book_info": "hello book 1",
        "planets_info": [
          "hello Earth",
          "Jupiter hello",
          "Earth hello",
        ]
      },

      "Book 2" : {
        "other_book_info": "hello book 2",
        "planets_info": [
          "hello Venus",
          "Pluto hello",
          "Mercury hello",
        ]
      }
  }
};
```

How can I return all Books (including the entire object) that have the word "earth" inside the planet_info array?

So it would return something like (notice "Book 2" is not there because it doesn't have the string **earth** inside the planets_info array and the planets_info array only contains the items that contain the **earth** string)

```javascript
const result = {
  "other_data" : "non important data",
  "exp" : {
      "Book 1" : {
        "other_book_info": "hello book 2",
        "planets_info": [
          "hello Earth",
          "Earth hello"
        ]
      }
  }
};

```

I have tried these queries without success:

 `exp[*][planets_info[~/${my_string}/i]]`
 `exp[*][*planets_info[~/${my_string}/i]]`
 `exp[*][*planets_info~/${my_string}/i]`

and without Regex:

 `exp[*][planets_info[~${my_string}]]`
 `exp[*][*planets_info[~${my_string}]]`
 `exp[*][*planets_info~${my_string}]`

I'm using json-jquery 2.1.1 ... Any idea why this is not working?

**Comment by mmckegg** [comment]
The correct query would be `exp[*][*planets_info~${my_string}]`. The reason this does not work is because partial matching only works on strings, or **whole** items in arrays. Regexp doesn't work with arrays. 

You can make this work by creating a helper function that can scan arrays for matches like this:

```js
var jsonQuery = require('json-query')

var data = {
  "other_data" : "non important data",
  "exp" : {
      "Book 1" : {
        "other_book_info": "hello book 1",
        "planets_info": [
          "hello Earth",
          "Jupiter hello",
          "Earth hello",
        ]
      },
      "Book 2" : {
        "other_book_info": "hello book 2",
        "planets_info": [
          "hello Venus",
          "Pluto hello",
          "Mercury hello",
        ]
      }
  }
}

var helpers = {
  contains: function (input, arg) {
    return Array.isArray(input) && input.some(x => x.includes(arg))
  }
}

console.log(jsonQuery('exp[*][*planets_info:contains(Earth)]', {
  data: data,
  locals: helpers
}).value)
```
