### ISSUE TITLE
Query matches not returning full object

### ISSUE THREAD

**Issue by JohnPolansky** [mmckegg/json-query#28]
I'm trying to make a match on an object inside of an array which is itself nested. I've provided a very ugly example normally the json object is much larger but I've simplified it here:

```
var jsonQuery = require('json-query')

var data = [
  {
    "cable_test": [
      { "results": "success", "status": "success" }
    ]
  },
  {
    "cable_test": [
      { "results": { "code": 500 }, "status": "error" }
    ]
  }
]

jsonQuery('cable_test[status=success]', {
  data: data
})
```

My objective is to return the FULL object for all matching entries. As you can see in this case it should return one full object. However instead all I get back is:

```
{
  "results": "success",
  "status": "success"
}
```

Now normally if you wrap the entire query in [*cable_test[status=success]] and that would return the full object however in this instance it returns a blank array.
```
[]
```
I'm not sure if there is an issue with nested queries and being able to read the full object but so far I haven't found combination that works. Any help appreciated.

**Comment by mmckegg** [comment]
Unfortunately json-query can't filter by nested params.

You could do something like this using helper functions:

```js
jsonQuery('[*:hasSuccess(cable_test)]', {
  data: data,
  locals: {
    hasSuccess: function (input, key) {
      return input[key].some(x => x.status === 'success')
    }
  }
})
```

Or a little more generic, using helpers to add support for nested queries:

```js
jsonQuery('[*:query(cable_test[status=success])]', {
  data: data,
  locals: {
    query: function (input, query) {
      return jsonQuery(query, {data: input}).value
    }
  }
})
```

**Comment by JohnPolansky** [comment]
Hey just wanted to say Thanks! for very quick response, it's definitely exactly what we needed. The 2nd helper example fit right into what we needed. Awesome work!
