### ISSUE TITLE
All values or query

### ISSUE THREAD

**Issue by micimize** [mmckegg/json-query#30]
Is there a way to include all results from an `or` query? Something like: 
```javascript
jsonQuery("[*element|sibling.child]", {
  data: {
    "element": "wanted element",
    "exclude": "exclude",
    "sibling": {
      "child": "wanted sibling child",
      "etc": "etc"
    }
 }
})
// => ["wanted element", "wanted sibling child"]
```

**Comment by mmckegg** [comment]
No, I don't think so. 

But you could do it with a helper function. Here's one way (with the most minimal helper possible):

```js
var helpers = {
  values: function (input, ...values) {
     return values
   }
}
jsonQuery(":values({element}, {sibling.child})", {
  locals: helpers,
  data: {
    "element": "wanted element",
    "exclude": "exclude",
    "sibling": {
      "child": "wanted sibling child",
      "etc": "etc"
    }
 }
})
```

All that is happening here is we use `{...}` sub queries, and then a helper to join them all into a single array. 

I do like your syntax proposed above though. It would fit quite nicely with the rest of the module.

**Comment by micimize** [comment]
ah, that's pretty elegant. I ended up baking my own "querying" solution because of the amount of custom functionality I wanted, but I'll keep this module in mind :-)
