### ISSUE TITLE
regexp match doesn't work

### ISSUE THREAD

**Issue by RiccardoFerrero1966** [mmckegg/json-query#52]
Hi, I test this code copying from npm json.query and also found in this git :

var jsonQuery = require("json-query")
var data = {
  people: [
    {name: 'Matt', country: 'NZ'},
    {name: 'Pete', country: 'AU'},
    {name: 'Mikey', country: 'NZ'}
  ]
}

var result = jsonQuery('people[*country~/^NZ/i]', allowRegexp=true, {
   data: data
});

console.log(result.value);
console.log(result);

the result is null
Please help me!

Thanks in advance

Riccardo

**Comment by mmckegg** [comment]
Should be:

```js
var result = jsonQuery('people[*country~/^NZ/i]', {
  data: data,
  allowRegexp: true
});
```

**Comment by RiccardoFerrero1966** [comment]
Thanks a lot!!!!! is working fine
