### ISSUE TITLE
expecting return array value, not only one

### ISSUE THREAD

**Issue by mezoo** [mmckegg/json-query#6]
Hi,
I'm trying to do a quick web service with json data : 

var profils = {
	"profil":[
		{"uuid": "BBBB",
		"name" : "avatar",
		"notification": true
		},
		{"uuid": AAAA,
		"name" : "avatar2",
		"notification": true
		},{..}]
}

I use json-query like this : 

jsonQuery(['profil[notification=?]',true],{data:profils})

I'm expected to have an array, but I see only the first element.
Can you tell me why ?

Thanks

**Comment by mmckegg** [comment]
json-query only returns the first match, that's unfortunately just part of it's design.

I think supporting multiple results would require some new syntax.

**Comment by resistdesign** [comment]
+1 For this feature, I expected this too.
